#1198.storybook css component whitebox
dso-toolkit/dso-toolkit pull request #1203
Opened 2021-06-28 11:30 UTC by daverhelst

**Implementatie informatie**

Geen

-----

**Pull request informatie**

Geen

2021-06-28 14:00 UTC, tfrijsewijk requested changes
Zoals besproken over Slack: We trekken de twee varianten uit elkaar en gaan ze als volwaardig component beschouwen. Jammer van de naamgeving, maar ze hebben zo weinig met elkaar te maken..

2021-06-30 15:51 UTC, tfrijsewijk requested changes

2021-07-01 11:08 UTC, daverhelst commented on packages/css/src/components/whitebox/whitebox.template.ts
> +        <img src=${image} alt="Indienen">
Zeker, die hebben we nu

2021-07-01 11:17 UTC, daverhelst commented on packages/css/src/components/whitebox-small/whitebox-small.scss
> +  @include whiteboxSmall_root();
Dit wordt aangepast in `tile_root()`

2021-07-02 07:18 UTC, daverhelst commented
Whitebox-small is nu Tile geworden, zowel in de CSS component, als de nunjucks file. `.dso-whitebox-small` heeft daardoor nu een deprecated stijling.

2021-07-10 16:17 UTC, tfrijsewijk requested changes

2021-07-10 16:17 UTC, tfrijsewijk commented on packages/css/src/components/tile/tile.scss
> +      @include tile-equal-heights_root();
De naam van deze mixin gaat nergens over - Uit welke filename komt deze mixin?

2021-07-10 16:17 UTC, tfrijsewijk commented on packages/sources/src/components/tile/tile.models.ts
> +  image: string;
`image` moet van het type `Image` zijn

2021-07-10 16:17 UTC, tfrijsewijk commented on packages/css/src/components/tile/tile.template.ts
> +          ${imageTemplate({ source: image, alt: ''})}
Hardcoded een lege alt? We willen juist representatieve demo's tonen

2021-07-10 16:17 UTC, tfrijsewijk commented on packages/css/src/components/whitebox/whitebox.scss
> +      @include whitebox-equal-heights_root();
Naam van mixin klopt niet

2021-07-10 16:17 UTC, tfrijsewijk commented on packages/css/src/components/whitebox/whitebox.template.ts
> +            ${iconTemplate({ icon: 'check' })}
Dat hier `check` staat is ook maar 'n voorbeeld.. Volgens mij kan hier elk icoon gebruikt worden.

2021-07-10 16:17 UTC, tfrijsewijk commented on packages/css/src/components/whitebox/whitebox.template.ts
> +          ${iconTemplate({ icon: 'angle-right' })}
Dit icoon is dus wél terecht. Idealiter zouden we dit eigenlijk met een icon after met `di()` mixin doen

2021-07-10 16:17 UTC, tfrijsewijk commented on packages/css/src/components/whitebox/whitebox.template.ts
> +        ${imageTemplate({ source: image, alt: 'Indienen'})}
:(

2021-07-10 16:17 UTC, tfrijsewijk commented on packages/sources/src/components/whitebox/whitebox.stories.ts
> +        icon: 'di di-check',
Hier staat het icoon wat je in die file hierboven hardcoded hebt geplaatst?

2021-07-13 12:28 UTC, tfrijsewijk commented on packages/css/src/components/whitebox/whitebox.template.ts
> +            ${iconTemplate({ icon: 'check' })}
Op regel 11 komt ie zelfs binnen...

2021-07-13 13:12 UTC, tfrijsewijk commented on packages/sources/src/components/whitebox/whitebox.args.ts
> +      type: 'boolean'
😢 

`icon` type boolean? Op regel 8 beweer je iets anders..

2021-07-13 13:13 UTC, tfrijsewijk commented on packages/sources/src/components/whitebox/whitebox.stories.ts
> +        icon: 'di di-check',
En icon is gewoon `check`

2021-07-13 13:16 UTC, tfrijsewijk commented on packages/sources/src/components/whitebox/whitebox.stories.ts
> +        richContent: 'Weet u al voor welke activiteiten u een vergunning moet aanvragen of een melding moet doen? Dan kunt u de aanvraag of melding direct indienen.',
En waarom is dit 'n string

![image](https://user-images.githubusercontent.com/9696261/125458333-f2e282ec-f387-407c-bc65-8184ececfc8f.png)

2021-07-13 13:34 UTC, tfrijsewijk commented on packages/sources/src/components/whitebox/whitebox.models.ts
> +  label: string;
Wat is het verschil tussen `label` en `iconText` ?

2021-07-13 13:36 UTC, tfrijsewijk commented on packages/sources/src/components/whitebox/whitebox.models.ts
> +  title?: string;
Volgens de `.njk` is `title` niet optioneel :(

2021-07-13 16:12 UTC, tfrijsewijk commented
Ik mis de CHANGELOG entry

2021-07-13 16:16 UTC, tfrijsewijk commented on packages/css/src/components/whitebox/whitebox.template.ts
> +        ${richContent}
Maar moet niet optioneel zijn

2021-07-13 16:18 UTC, tfrijsewijk commented on packages/css/src/components/tile/tile.scss
> +.dso-whitebox-small { // DEPRECATED
Ik geloof bijna niet dat je dit getest hebt.. Want waar is de rest van de styling op `.dso-whitebox-small` ?

2021-07-13 16:19 UTC, tfrijsewijk commented
![image](https://user-images.githubusercontent.com/9696261/125488573-fb7966f6-496a-4688-b8c8-4d38c3ce7bd6.png)

Dit ziet er ook goed uit

2021-07-13 16:26 UTC, tfrijsewijk commented on packages/dso-toolkit/components/Voorbeelden/10-Patronen/row-equal-heights.njk
> +      {% render '@tile', { label: whiteboxSmall.label, source: whiteboxSmall.source } %}
Bewust local variable `whiteboxSmall` laten bestaan?

2021-07-13 16:56 UTC, merged