#1251.storybook css component   application header
dso-toolkit/dso-toolkit pull request #1260
Opened 2021-08-19 11:15 UTC by PieterVerheij

2021-08-19 13:38 UTC, tfrijsewijk requested changes

2021-08-19 13:38 UTC, tfrijsewijk commented on packages/css/src/components/application-header/application-header.scss
> +.dso-app-heading {
Bijzonder dat de bestandsnamen `application-header` heten, maar het component `app-heading`. Zullen we dit synchroniseren?

`app-heading` is slecht gekozen, maar laten we daar de API niet op aanpassen. Dat is een misstap. Ik stel voor dat we de bestandsnamen aanpassen naar `app-heading.scss` enz.

2021-08-19 13:39 UTC, tfrijsewijk commented
En zou je master in deze branch willen mergen?

2021-08-31 13:28 UTC, gofix commented on packages/dso-toolkit/src/styles/dso.scss
> +// @import "components/application-heading"; -> Moved to @dso-toolkit/styling
Eigenlijk niet. Voorheen administreerden we dit wel zo, maar toen bestond inderdaad `@dso-toolkit/styling` nog. Nu is het wellicht beter om het echte verhuisdoel aan te duiden.

2021-09-01 09:34 UTC, tfrijsewijk approved these changes

2021-09-01 09:35 UTC, merged