#1250.Storybook CSS Component - List Button + Input Number + Button Group
dso-toolkit/dso-toolkit pull request #1265
Opened 2021-09-06 09:26 UTC by daverhelst

**Implementatie informatie**

Geen

-----

**Pull request informatie**

Geen

2021-09-13 08:07 UTC, tfrijsewijk requested changes
Zie review items.

Verder: Hoe sta jij er tegenover om componenten die nooit als Web Component opgeleverd gaan worden of binnen het Shadow DOM gebruikt gaan worden niet meer als mixin vanuit `/sources` aan te leveren maar direct in `/css` op te nemen?

2021-09-13 08:07 UTC, tfrijsewijk commented on packages/css/src/components/list-button/list-button.template.ts
> +          <button type=${type} class="btn dso-list-button ${classMap({ 'dso-selected': count > 0 })}" ?disabled=${disabled}>
Op regel 24 begint nagenoeg dezelfde code, kan je dit opdrogen? (DRY)

2021-09-13 08:07 UTC, tfrijsewijk commented on packages/css/src/components/list-button/list-button.template.ts
> +          ${count == 1 ? html`${iconTemplate({ icon: 'check' })}` : nothing}
En je kan deze ternary samenvoegen met de ternary op regel 29

2021-09-13 08:07 UTC, tfrijsewijk commented on packages/css/src/components/list-button/list-button.template.ts
> +        <button type=${type} class="btn dso-list-button ${classMap({ 'dso-selected': count > 0 })}" ?disabled=${disabled}>
Hetzelfde geldt voor labels op componenten. Als het label 'n eigenschap van het component is mag het gewoon hardcoded worden opgenomen.

Pas configureerbaar maken als het contextafhankelijk is of de afnemers hebben de vrijheid om er 'n andere tekst te plaatsen.

Neem het PR goed door, er meer kandidaten.

2021-09-16 11:16 UTC, daverhelst commented on packages/css/src/components/list-button/list-button.scss
> +.dso-btn-group {
Wat vind jij er dan van om een nieuwe mixin `button-group_sibling()` te maken, die exact hetzelfde doet als de `list-button_sibling()`, maar geldt voor de `.dso-btn-group` in een `.dso-list-button` en `.dso-btn-group`.

Dan krijg je dus:
```
.dso-list-button {
  @include list-button_root();

  + .dso-list-button {
    @include list-button_sibling();
  }

  + .dso-btn-group {
    @include button-group_sibling();
  }
}
```

en

```
.dso-btn-group {
  @include button-group_root();

  + .dso-list-button {
    @include list-button_sibling();
  }

  + .dso-btn-group {
    @include button-group_sibling();
  }
}
```

2021-09-16 11:17 UTC, daverhelst commented on packages/sources/src/styling/mixins/state-styling.scss
> +@mixin state-styling($background-color: inherit, $border-color: inherit, $color: inherit) {
hij wordt in `input-number.scss` en `list-button.scss` gebruikt.

2021-09-16 11:28 UTC, daverhelst commented on packages/css/src/components/input-number/input-number.template.ts
> +      ${buttonTemplate({ type: 'button', label: minusButtonLabel, variant: null, modifier: 'btn btn-link', disabled: minusButtonInactive, icon: { icon: 'minus-square' }, iconMode: 'only' })}
Je hebt gelijk, ik pas het aan

2021-09-16 11:44 UTC, daverhelst commented on packages/css/src/components/list-button/list-button.template.ts
> +          ${count == 1 ? html`${iconTemplate({ icon: 'check' })}` : nothing}
Kun je dat uitleggen? Die op regel 28 toont wel of geen icon, die op regel 29 toont een `<span class="dso-count">${count}x</span>`.

Of zeg je dat die ook samengevoegd kunnen worden?

2021-09-17 05:20 UTC, daverhelst commented
> Verder: Hoe sta jij er tegenover om componenten die nooit als Web Component opgeleverd gaan worden of binnen het Shadow DOM gebruikt gaan worden niet meer als mixin vanuit `/sources` aan te leveren maar direct in `/css` op te nemen?

Ik weet het niet. We moeten toch al een folder maken waarin de .args, .models en .stories zitten, dus dan vind ik het ook niet erg om de styling daarbij te hebben die in mixins staan. Maar ik snap wel je gedachte,

2021-09-17 06:18 UTC, daverhelst commented on packages/css/src/components/list-button/list-button.template.ts
> +        <button type=${type} class="btn dso-list-button ${classMap({ 'dso-selected': count > 0 })}" ?disabled=${disabled}>
Ik heb de componenten nagelopen en de zaken waarvan ik denk dat ze vaststaan, als zodanig hardcoded ingevuld.

2021-09-20 07:38 UTC, tfrijsewijk commented on packages/sources/src/styling/mixins/state-styling.scss
> +@mixin state-styling($background-color: inherit, $border-color: inherit, $color: inherit) {
OK!

2021-09-20 08:36 UTC, tfrijsewijk commented on packages/css/src/components/list-button/list-button.template.ts
> +          ${count == 1 ? html`${iconTemplate({ icon: 'check' })}` : nothing}
Het is niet meer van toepassing door jouw laatste refactor, ziet er goed uit zo

2021-09-20 08:36 UTC, tfrijsewijk commented on packages/css/src/components/list-button/list-button.scss
> +.dso-btn-group {
Straks even naar kijken?

2021-09-20 11:02 UTC, daverhelst commented on packages/css/src/components/list-button/list-button.template.ts
> +      ${sublabel && html`<span class="dso-sublabel">${sublabel}</span>`}
Dit wil je dan ook voor de ternary op regel 15, lijkt me. Ik pas het toe

2021-09-20 11:35 UTC, daverhelst commented on packages/css/src/components/list-button/list-button.template.ts
> +function listButtonButtonTemplate({ disabled, label, sublabel, subcontent, count }: ListButton) {
Wat vind je van `listButtonElementTemplate` of `listButtonWrapperTemplate`?

2021-09-20 12:26 UTC, tfrijsewijk commented on packages/css/src/components/list-button/list-button.template.ts
> +function listButtonButtonTemplate({ disabled, label, sublabel, subcontent, count }: ListButton) {
Of `listButtonComponentTemplate()` ?

2021-09-20 13:08 UTC, daverhelst commented
Naar aanleiding van een overleg tussen @tfrijsewijk en ik is besloten om `dso-btn-group` en `dso-list-button` qua styling samen te voegen. Dit is een logische stap omdat de `dso-btn-group` alleen in het wereldje van de `dso-list-button` leeft.

2021-09-20 13:09 UTC, daverhelst commented on packages/css/src/components/list-button/list-button.template.ts
> +function listButtonButtonTemplate({ disabled, label, sublabel, subcontent, count }: ListButton) {
Daar kan ik prima mee leven

2021-09-21 07:25 UTC, daverhelst commented on packages/sources/src/components/input-number/input-number.scss
> +@mixin input-number_root() {
Zoals besproken, deze gaan naar een eigen mixin genaamd `list-button_input-number()` die zal leven in `.dso-btn-group`

2021-09-21 07:27 UTC, daverhelst commented on packages/css/src/components/list-button/list-button.scss
> +.dso-btn-group {
Besloten is om `.dso-list-button` en `.dso-btn-group` op een gelijk niveau te behandelen. De stijling van beide zal in 1 file onder gebracht worden, namelijk `list-button.scss`. Ik heb nu nog 1 sibling mixin staan, `list-button_sibling()` en de aanroep omgebouwd naar:

```
.dso-list-button,
.dso-btn-group {
  + .dso-list-button,
  + .dso-btn-group {
    @include list-button_sibling();
  }
}
```

2021-09-29 13:49 UTC, tfrijsewijk approved these changes

2021-09-29 13:50 UTC, merged