#1342 toetsenbordinteractie tree view werkt niet met nvda
dso-toolkit/dso-toolkit pull request #1352
Opened 2021-11-22 18:28 UTC by smvandermeulen

Bevat ook oplossing voor #1348.

2021-11-23 08:07 UTC, tfrijsewijk requested changes
Kan jij naar mijn bevindingen kijken? Als je het zo wilt laten zal ik 'm lokaal rebasen, CHANGELOG entry toevoegen en mergen.

Als je gaat sleutelen, wil jij dan rebasen op master en de CHANGELOG entry toevoegen?

2021-11-24 10:43 UTC, smvandermeulen commented on packages/core/src/components/tree-view/tree-item.tsx
> +        {item.items?.map((childItem: TreeViewItem<string>, index: number, org: TreeViewItem<string>[]) =>
Aangepast

2021-11-24 10:44 UTC, smvandermeulen commented on packages/core/src/components/tree-view/tree-item.tsx
> +          ? <dso-progress-indicator size="small" label="Resultaten laden: een moment geduld alstublieft." />
De `dso-progress-indicator` staat nu buiten de `ul`.

2021-11-24 15:18 UTC, tfrijsewijk commented
* 67851a422ad5612562c67f961eb46d721d98bba7 merged into master: 1d8df25dd615e9a6c81df8a054346137098adee8
* 0e0e606ec4971a062150167c9f8079f5224c9965 en 351b3720f48ed81872aa8096f2f19170ec77e7f8 merged into master: 755a796dc9d0b47b5f2c4d9ef657664109fc8e8c

2021-11-24 15:18 UTC, closed without merging