#1188.Storybook CSS Component - Image
dso-toolkit/dso-toolkit pull request #1435
Opened 2022-02-22 12:41 UTC by daverhelst

- opschoning img-rounded
- opschoning img-thumbnail

2022-02-24 09:43 UTC, tfrijsewijk reviewed
Ziet er goed uit.

In het issue staat "deprecaten", in de CHANGELOG staat "verwijderen".

De change laat ook zien dat de twee varianten zijn verwijderd. Kan je het verschil in scope en uitwerking toelichten?

2022-02-24 10:16 UTC, daverhelst commented
Net tijdens refinement ter verduidelijking gevraagd, want in het issue stond inderdaad deprecaten, maar in een commentaar werd door Michiel gemeld dat ze verwijderd konden worden.

Nu besproken; het wordt deprecated, dus ik zal wat wijzigingen moeten terugdraaien en aanpassen.

2022-02-24 11:53 UTC, daverhelst commented
Voor nu is gekozen om de deprecation stijling toe te passen en deze varianten in de Fractal omgeving te laten staan. Ze worden niet meegenomen naar de HTML/CSS Storybook.

2022-02-24 13:34 UTC, tfrijsewijk requested changes

2022-02-24 13:34 UTC, tfrijsewijk commented on packages/sources/src/components/image/image.scss
> +  border: 8px solid $dso-invalid-color;
De variable `$thumbnail-border` op regel 3 wordt nu nergens meer gebruikt en mag weg.

Verder vind ik het niet zo fraai dat dit met een border wordt gedaan: Dit verstoort de opbouw van de pagina, zie Percy:

![image](https://user-images.githubusercontent.com/9696261/155533307-1f333d6b-69c9-44d5-b022-a438cabca5b6.png)


Ik heb liever dat je dit non-intrusive maakt met bv. outline.

2022-02-24 13:34 UTC, tfrijsewijk commented on CHANGELOG.md
> +* **sources:** CSS Component Image; deprecation img-rounded, img-thumbnail in fractal ([#1188](https://github.com/dso-toolkit/dso-toolkit/issues/1188))
Graag een inhoudelijk kloppende titel voor het issue opstellen en die dupliceren in de CHANGELOG.md.

("in fractal" is een detail wat niet interessant is voor de buitenwereld en ook niet waar: deprecation is dso-toolkit eigen)

2022-02-24 16:24 UTC, tfrijsewijk approved these changes

2022-02-24 16:25 UTC, merged

2022-02-28 11:02 UTC, tfrijsewijk commented
Lokaal gemerged met https://github.com/dso-toolkit/dso-toolkit/commit/652edc035de26fc4dad72e8f6669fe22e37c88ad