#1253.css component shopping cart
dso-toolkit/dso-toolkit pull request #1450
Opened 2022-03-03 11:25 UTC by daverhelst

2022-03-03 21:10 UTC, tfrijsewijk requested changes
🛐 Diep onder de indruk.. fantastisch gedaan.

2022-03-03 21:10 UTC, tfrijsewijk commented on packages/css/src/components/shopping-cart/shopping-cart.scss
> +    @extend .form-control; /* stylelint-disable-line scss/at-extend-no-missing-placeholder -- is an extend on a bootstrap class */
Probeer `@include form-control();` eens.

2022-03-03 21:10 UTC, tfrijsewijk commented on packages/css/src/components/shopping-cart/shopping-cart.template.ts
> +                                <input type="text" class="dso-edit-name" id="additive-${item.id}" value="${item.additive}" />
```suggestion
                                <input type="text" class="dso-edit-name" id="additive-${item.id}" value=${item.additive} />
```

Graag ook de rest van de files checken: Als je direct een interpolated value in een attribute stopt zijn de quotes niet nodig (en worden zelfs afgeraden door het lit team)

2022-03-03 21:10 UTC, tfrijsewijk commented on packages/css/src/components/shopping-cart/shopping-cart.template.ts
> +function accumulateItems(items: any) {
Kan je deze drie functies niet typeren met `ShoppingCartItem` en/of `ShoppingCartSubitem` ?

2022-03-04 07:15 UTC, daverhelst commented on packages/css/src/components/shopping-cart/shopping-cart.scss
> +    @extend .form-control; /* stylelint-disable-line scss/at-extend-no-missing-placeholder -- is an extend on a bootstrap class */
Ah, fijn!

2022-03-07 14:54 UTC, tfrijsewijk approved these changes

2022-03-07 15:11 UTC, merged