#1638-pagination-web-component
dso-toolkit/dso-toolkit pull request #1656
Opened 2022-07-21 13:27 UTC by svrijsewijk

2022-07-21 14:36 UTC, tfrijsewijk requested changes
Nav. gezamenlijk review

2022-07-21 14:36 UTC, tfrijsewijk commented on packages/core/src/components/pagination/pagination.scss
> +@import "../../icon/di";
_of_ gebruik maken van `<dso-icon>`

2022-07-21 14:36 UTC, tfrijsewijk commented on packages/core/src/components/pagination/pagination.tsx
> +  count!: number;
In overleg hernoemen naar `totalPages`.

2022-07-21 14:36 UTC, tfrijsewijk commented on packages/core/src/components/pagination/pagination.tsx
> +  current!: number;
In overleg hernoemen naar `currentPage`.

2022-07-21 14:36 UTC, tfrijsewijk commented on packages/core/src/components/pagination/pagination.tsx
> +  createLink!: (page: number) => string;
In overleg hernoemen naar `formatHref()`.

2022-07-21 14:36 UTC, tfrijsewijk commented on packages/core/src/components/pagination/pagination.tsx
> +    e.preventDefault();
Inspiratie opdoen bij Angular's `routerLink` directive voor het afvangen van bv. CTRL + Click.

2022-07-21 14:36 UTC, tfrijsewijk commented on packages/core/src/components/pagination/pagination.tsx
> +      <nav aria-label={this.label}>
`<nav>` uit het component tillen, we zijn tot de conclusie gekomen dat dit niet het begin van Pagination is maar dat deze semantiek bij de afnemer ligt.

2022-07-21 14:36 UTC, tfrijsewijk commented on packages/sources/src/components/pagination/pagination.models.ts
> +  onSelectPage: (e: CustomEvent<any>) => void;
Hier mist `formatHref()`.

2022-07-21 18:14 UTC, svrijsewijk commented on packages/core/src/components/pagination/pagination.interfaces.ts
> +  originalEvent: MouseEvent;
De interface van de onClick event van Stencil geeft aan dat het MouseEvent is. Dat event valt niet te assignen aan een parameter PointerEvent.

2022-07-21 18:15 UTC, svrijsewijk commented on packages/core/src/components/pagination/pagination.scss
> +@import "~@dso-toolkit/sources/src/styling/variables";
Blijkt toch lastig, het valt inderdaad over $u4

2022-07-22 10:02 UTC, tfrijsewijk commented on packages/core/src/components/pagination/pagination.interfaces.ts
> +  originalEvent: MouseEvent;
Oki, dank voor het uitzoeken

2022-07-22 10:03 UTC, tfrijsewijk commented on packages/core/src/components/pagination/pagination.scss
> +@import "~@dso-toolkit/sources/src/styling/variables";
Ja idd.. Dat moeten we maar eens 'n andere keer oppakken.

2022-07-22 10:08 UTC, tfrijsewijk commented on packages/react/src/components/pagination/pagination.template.tsx
> +      selectPage={onSelectPage}
De React bindings van Stencil prefixen `@Event()`s met `on`: Deze property zou volgens mij `onSelectPage` moeten zijn, want de events tonen niet in Storybook: https://react.dso-toolkit.nl/_1638-pagination-web-component/?path=/story/pagination--pagination

2022-07-22 10:52 UTC, merged