#1669 header click events uitbreiden en functionaliteit ook tonen bij geen menu items
dso-toolkit/dso-toolkit pull request #1679
Opened 2022-08-03 08:58 UTC by svrijsewijk

en ook
#1662 header ook uitloggen zonder logoutUrl

2022-08-03 12:36 UTC, svrijsewijk commented on cypress/integration/core/header.spec.ts
> +      (element as any).mainMenu = items;
dit is een beetje jammer, ik had liever `if(element instanceof HTMLDsoHeaderElement)` willen doen maar dat gaat helaas niet.

2022-08-03 14:04 UTC, benheldoorn requested changes
Verder vind ik het wel jammer dat er zowel single en double quotes gebruikt worden, maar dat is een bijna kansloze exercitie om dat strak te houden. We kunnen het natuurlijk gewoon los laten, het is mij om het even.

2022-08-03 14:04 UTC, benheldoorn commented on packages/sources/src/components/header/header.args.ts
> +  onHeaderClick: {
Als je hier nog `...noControl,` voor zet krijg je niet zo'n nutteloos regeltje onder "Controls"

2022-08-03 14:40 UTC, svrijsewijk commented on CHANGELOG.md
> +* **BREAKING: core + react:** Header: Removed `menuItemClick` event emitter. Added `headerClick` event emitter, deze emit wanneer de gebruiker op een menu item, profiel link, user home, login/logout
Ah ja, goed gezien 🙂

2022-08-03 14:43 UTC, svrijsewijk commented
> Verder vind ik het wel jammer dat er zowel single en double quotes gebruikt worden, maar dat is een bijna kansloze exercitie om dat strak te houden. We kunnen het natuurlijk gewoon los laten, het is mij om het even.

Volgens mij gaan we naar single quote toe met de doorontwikkeling. Ik probeer bij bestaande code zo veel mogelijk de stijl van het bestand aan te houden. Bij de tests vond ik het de moeite om voor de grote stukken de switchen naar single quote. Zo blijft de blame op de file zo bruikbaar mogelijk nadat de code-formatting commit eroverheen gaat.

2022-08-04 13:36 UTC, benheldoorn approved these changes

2022-08-04 14:20 UTC, merged