#1647 v2 gebruiker kan tekstgrootte niet wijzigen dmv browser instellingen
dso-toolkit/dso-toolkit pull request #1718
Opened 2022-08-19 12:10 UTC by PieterVerheij

2022-08-22 14:58 UTC, svrijsewijk requested changes

2022-08-24 13:42 UTC, PieterVerheij commented on packages/sources/src/components/input-number/input-number.scss
> +    height: 1.5em;
aangepast

2022-08-24 13:44 UTC, PieterVerheij commented on packages/sources/src/components/pagination/pagination.scss
> +    line-height: calc($dso-pagination-item-size - $dso-pagination-item-border-size * 2);
Dit komt eruit (`line-height: calc(2rem - 4px)`), het lijkt dus wel goed te gaan?
![image](https://user-images.githubusercontent.com/25430835/186434231-7d603258-1ce9-4982-9ca5-ec0d55aa3ec8.png)

2022-08-24 13:46 UTC, PieterVerheij commented on packages/sources/src/styling/global/code.scss
> +  font-size: 0.9em;
aangepast

2022-08-24 13:52 UTC, PieterVerheij commented on packages/sources/src/styling/mixins/form-control.scss
> +$dso-form-control-height: calc(($padding-base-vertical + 1px) * 2 + $dso-form-control-border-width * 2 + $dso-font-size-base * 1.5);
Ook hier lijkt het gewoon goed te gaan: `line-height: calc(16px + 1.5rem)`?
![image](https://user-images.githubusercontent.com/25430835/186435976-8b01b30e-99a4-4ef6-b18e-ec72e17f22bc.png)

2022-08-24 13:52 UTC, PieterVerheij commented on packages/sources/src/styling/mixins/step-counter.scss
> +$dso-step-counter-dim: 2rem;
aangepast

2022-08-24 14:03 UTC, PieterVerheij commented on packages/sources/src/styling/variables/typography.scss
> +$dso-font-size-base: 1rem;
@svrijsewijk waar zou je die libs map plaatsen en waar zou je die scss dan import-en?

2022-08-24 14:11 UTC, PieterVerheij commented on packages/sources/src/styling/variables/typography.scss
> +$dso-font-size-base: 1rem;
aangepast, verhuisd naar `\packages\dso-toolkit\libs\bootstrap\_variables.scss`

2022-08-25 09:36 UTC, PieterVerheij commented on packages/sources/src/styling/variables/typography.scss
> +$dso-font-size-base: 1rem;
Dit gaat toch niet goed (snap niet waarom dit niet eerder naar voren kwam):
![image](https://user-images.githubusercontent.com/25430835/186630670-b054996a-f447-452f-b5bc-c9025bb24315.png)
![image](https://user-images.githubusercontent.com/25430835/186630710-d8b22efc-9740-44eb-8779-cd0cbff562fc.png)

2022-08-25 09:42 UTC, PieterVerheij commented on packages/sources/src/styling/variables/typography.scss
> +$dso-font-size-base: 1rem;
`$line-height-computed ` komt best wel vaak voor, en niet alleen `line-height` maar het wordt ook vaak gebruikt voor `margin-bottom` e.d.

2022-08-25 10:36 UTC, PieterVerheij commented on packages/sources/src/styling/global/code.scss
> +  font-size: 0.9em;
Correctie: dit moet toech relatief worden, anders valt dit om:
![image](https://user-images.githubusercontent.com/25430835/186643132-129db1bf-0d99-4941-a5ec-e22c74371100.png)

Ik draai de wijziging helemaal terug (dus naar `90%`).

2022-08-29 12:05 UTC, tfrijsewijk commented on packages/sources/src/components/pagination/pagination.scss
> +    line-height: calc($dso-pagination-item-size - $dso-pagination-item-border-size * 2);
Onbegrijpelijk -- Ik ga hier nog even wat onderzoek naar doen..

2022-08-29 12:06 UTC, tfrijsewijk commented on packages/sources/src/styling/mixins/form-control.scss
> +$dso-form-control-height: calc(($padding-base-vertical + 1px) * 2 + $dso-form-control-border-width * 2 + $dso-font-size-base * 1.5);
Ga ik onderzoeken

2022-08-29 12:38 UTC, tfrijsewijk commented on packages/dso-toolkit/libs/bootstrap/_variables.scss
> +@use "sass:math";
Deze is niet meer nodig

2022-08-30 11:22 UTC, tfrijsewijk commented on packages/sources/src/components/pagination/pagination.scss
> +    line-height: calc($dso-pagination-item-size - $dso-pagination-item-border-size * 2);
Gevonden! In node-sass en tot `sass<1.40.0` MOET je expliciet interpoleren, vanaf `sass^1.40.` mag je meteen de variablen gebruiken

2022-08-30 11:22 UTC, tfrijsewijk commented on packages/sources/src/styling/mixins/form-control.scss
> +$dso-form-control-height: calc(($padding-base-vertical + 1px) * 2 + $dso-form-control-border-width * 2 + $dso-font-size-base * 1.5);
Gevonden! In node-sass en tot `sass<1.40.0` MOET je expliciet interpoleren, vanaf `sass^1.40.` mag je meteen de variablen gebruiken

2022-08-30 11:23 UTC, tfrijsewijk commented on packages/sources/src/styling/variables/typography.scss
> +$dso-font-size-base: 1rem;
Zoals overlegd met @PieterVerheij, we blijven met twee systemen werken. Bij het verhuizen van de componenten stappen we over.

2022-08-30 13:20 UTC, tfrijsewijk commented
Lokaal gemerged met https://github.com/dso-toolkit/dso-toolkit/commit/c1cfa3c81efcc4993e3f12fba3d912d80718739c

2022-08-30 13:20 UTC, closed without merging