#1695 Afbeelding in dso-image-overlay alleen zoomable maken als de af…
dso-toolkit/dso-toolkit pull request #1720
Opened 2022-08-21 17:38 UTC by svrijsewijk

…beelding niet in de container past

2022-08-22 09:53 UTC, svrijsewijk commented on packages/core/src/components/image-overlay/image-overlay.tsx
> +  isImageZoomable(imageElement: HTMLImageElement): void {
Dit kan beter setZoomable heten

2022-08-22 10:07 UTC, svrijsewijk commented on packages/core/src/components/image-overlay/image-overlay.tsx
> +    imgElement.onload = (event) => {
hiermee overschrijven we mogelijk een afnemer die ook `onload =` heeft gezet. Dit kan beter met `addEventListener();`

2022-08-24 06:01 UTC, tfrijsewijk requested changes
We hebben toch nog wat over het hoofd gezien..

Anders ook nog even bellen? Ik vraag mij af of de code simpeler kan worden als we `this.resizeObserver.observe(this.host)` doen ipv op `imgElement`.

2022-08-24 09:23 UTC, svrijsewijk commented
> We hebben toch nog wat over het hoofd gezien..
> 
> Anders ook nog even bellen? Ik vraag mij af of de code simpeler kan worden als we `this.resizeObserver.observe(this.host)` doen ipv op `imgElement`.

Ik denk dat het meest zuivere is om op de `imgElement` te observen, het is voor een afnemer mogelijk om de host `display: block` te geven, waarbij die resized op bijvoorbeeld viewport changes maar de image even groot kan blijven.

2022-08-24 09:36 UTC, svrijsewijk commented on packages/core/src/components/image-overlay/image-overlay.tsx
> +  private resizeObserver = new ResizeObserver(debounce(() => {
Ik heb het aangepast maar tijdens het aanpassen ontstonden er ook weer twijfels. Bij het instantieren van deze class vind ik het niet zo heel gek om ook een ResizeObserver te instantieren. De  observe() hangt immers wel aan een lifecycle.

Omdat het instantieren van de observer nu in een lifecycle gebeurt krijg je naar mijn inziens veel nutteloze checks of de property wel defined is.

2022-08-24 09:38 UTC, svrijsewijk commented on packages/core/src/components/image-overlay/image-overlay.tsx
> +    if (imgElement.complete) {
> Idee: Kan je het toevoegen van een event listener op load niet in de else van deze voorwaarde plaatsen?

De load hebben we altijd nodig doordat de afnemer de `src` van de `img` later nog kan vervangen.

2022-08-24 09:39 UTC, svrijsewijk commented on packages/core/src/components/image-overlay/image-overlay.tsx
> +    if (imgElement.complete) {
Suggestie van @tfrijsewijk om de `capture` optie te bekijken van de eventListener. Daarmee hoeven we niet meer per `img` een eventListener te maken. Maar zit er 1 op de `<Host>` die van child `img` de load events ook opvangt.

2022-08-24 09:40 UTC, svrijsewijk commented on cypress/integration/core/image-overlay.spec.ts
> +  it.only('should only have overlay available if image is zoomable' , () => {
ja mee eens, technisch is er geen verschil maar goed om vast te leggen in een test.

2022-08-24 18:48 UTC, merged