#1708 Viewer grid: toegankelijkheid bediening breedte kaartpaneel
dso-toolkit/dso-toolkit pull request #1739
Opened 2022-09-05 08:17 UTC by LukeVerlaan

2022-09-05 09:12 UTC, tfrijsewijk requested changes
Ziet er goed uit! Zie opmerkingen.

2022-09-05 09:12 UTC, tfrijsewijk commented on cypress/integration/viewer-grid.spec.ts
> +  it('should say the right phrase uppon size change', () => {
De correcte spelling is "upon". Daarnaast zie ik de verwachting explicieter: Welke phrase wordt er dan uitgesproken?

2022-09-05 09:12 UTC, tfrijsewijk commented on cypress/integration/viewer-grid.spec.ts
> +      .should('eq', 'polite')
Graag de volledige notatie gebruiken

2022-09-05 09:12 UTC, tfrijsewijk commented on cypress/integration/viewer-grid.spec.ts
> +    cy.get('@root')
Je zou een functie `shouldHavePhrase(size: string);` kunnen maken. Als je die dan IN deze `it()` maakt heb je 'n lokale helper functie.

2022-09-05 09:12 UTC, tfrijsewijk commented on packages/core/src/components/viewer-grid/viewer-grid.tsx
> +    this.srSize = this.srSize === 'breed' ? 'middel' : 'smal';
Het is onnodig om twee keer de huidige staat bij te houden. Je kan in de `render()` prima de `mainSize` resolven tot een leesbaar label.

Je kan een `private getSizeLabel(): string` maken, of een `private sizeLabelMap: { [size: MainSize]: string };` met `{this.sizeLabelMap[this.mainSize]}`.

2022-09-05 09:12 UTC, tfrijsewijk commented on packages/core/src/components/viewer-grid/viewer-grid.tsx
> +        <div aria-live="polite" class="dso-map-panel">
Is dit de juiste plek voor de `aria-live="polite"` ? Ik vermoed dat ie OOK de inhoud van de knoppen gaat voorlezen.. Volgens mij zegt de scope van het issue ook dat de aria-live="polite" OP de `span.sr-only` moet.

2022-09-05 11:39 UTC, tfrijsewijk reviewed
Zie commentaar, wat mij betreft is dit merge waardig. Ik leg het bij jou neer of je nog wat met de opmerkingen gaat doen.

2022-09-05 11:39 UTC, tfrijsewijk commented on packages/core/src/components/viewer-grid/viewer-grid.tsx
> +          <span class="sr-only" aria-live="polite">breedte tekstpaneel: {this.sizeLabelMap.get(this.mainSize)}</span>
Ik denk dat deze nog 'n beetje moet inspringen..

2022-09-05 11:39 UTC, tfrijsewijk commented on packages/core/src/components/viewer-grid/viewer-grid.tsx
> +  private sizeLabelMap = new Map<MainSize, string>([
Met het gebruik van Map is natuurlijk niets mis, maar het nadeel daarvan is dat het maar weinig afdwingt over de inhoud.

Ik heb even wat gespeeld met de TypeScript playground:

![image](https://user-images.githubusercontent.com/9696261/188440405-d618e83a-9202-4c02-9550-de31055c3c65.png)

Kijk maar of je het de moeite vindt.

2022-09-05 13:10 UTC, tfrijsewijk approved these changes

2022-09-05 13:11 UTC, tfrijsewijk commented
Ziet er goed uit @LukeVerlaan.

@timveld @hansgrimm Kunnen jullie testen? https://storybook.dso-toolkit.nl/_1708-Viewer-grid-toegankelijkheid-bediening-breedte-kaartpaneel/?path=/story/core-viewer-grid--viewer-grid

2022-09-07 10:40 UTC, timveld commented
@tfrijsewijk getest en (zoals in slack besproken) gaat het in Firefox mis, omdat alleen de wijziging van het label wordt voorgelezen (dus als de breedte smal wordt zegt NVDA alleen "sma"). Vermoedelijk heeft dat te maken met de manier waarop het label vanuit de javascript wordt geupdated. 
Als je het in een release wilt meenemen kan dat wel, dan maak ik een nieuw issue waarin we kunnen proberen bovengenoemd probleem op te lossen.

2022-09-09 07:10 UTC, tfrijsewijk commented
@timveld Ik heb `aria-atomic="true"` gezet: https://storybook.dso-toolkit.nl/_1708-Viewer-grid-toegankelijkheid-bediening-breedte-kaartpaneel/?path=/story/core-viewer-grid--viewer-grid

2022-09-09 09:48 UTC, hansgrimm commented
Als dit inderdaad de oplossing is: helemaal top!
Er zou geen probleem moeten zijn met ff+NVDA, zie hier: https://a11ysupport.io/tests/tech__aria__aria-atomic-divs

2022-09-09 10:33 UTC, timveld commented
Aria-atomic lost het probleem op!

2022-09-09 10:45 UTC, hansgrimm commented
Daar zit ik dan op mijn vrije vrijdag, helemaal ontroerd 😊

2022-09-09 10:49 UTC, hansgrimm commented
Scheelt weer een extra ticket 🤘

2022-09-09 11:41 UTC, tfrijsewijk approved these changes

2022-09-09 11:41 UTC, merged