#1706 react storybook event emitters nalopen
dso-toolkit/dso-toolkit pull request #1778
Opened 2022-09-21 10:01 UTC by LukeVerlaan

Componenten: Datepicker, Info button, Label, Selectable, Tooltip.

- event emitters aangepast

2022-09-22 12:05 UTC, LukeVerlaan commented
In `packages\react\src\react-component-lib\utils\attachProps.ts` zit een functie `isCoveredByReact`.

Hierin staat:
`const eventName = 'on' + eventNameSuffix;`
 `let isSupported = eventName in document;`
 
`isSupported` checkt of events voorkomen als property op `document `. Als dit zo is, wordt er geen mapping gelegd voor de React Bindings en gaat het stuk.

2022-09-26 06:59 UTC, svrijsewijk requested changes

2022-09-26 06:59 UTC, svrijsewijk commented on packages/react/src/components/label/label.template.tsx
> +      onRemoveClick={onRemoveClick}
`onDsoRemoveClick` (dit event gaat nog niet goed in de react storybook)

2022-09-26 06:59 UTC, svrijsewijk commented on packages/react/src/components/info-button/info-button.template.tsx
> +      secondary={secondary}
goed gezien 😄

2022-09-26 14:45 UTC, closed without merging