#2034 Webcomponent dso-expandable
dso-toolkit/dso-toolkit pull request #2102
Opened 2023-05-03 14:55 UTC by LukeVerlaan

2023-05-08 09:26 UTC, svrijsewijk requested changes

2023-05-08 09:26 UTC, svrijsewijk commented on packages/core/src/components/accordion/components/accordion-section.tsx
> +function isExpandable(element: HTMLElement | ExpandableInterface | null): element is ExpandableInterface {
hoort deze niet ge-exporteerd te worden bij `dso-expandable`?

2023-05-08 12:49 UTC, LukeVerlaan commented on packages/core/src/components/expandable/readme.md
> +| `animationOffset` | `animation-offset` |             | `number \| undefined`  | `undefined` |
Deze property wordt gebruikt als waarde voor de property height van `animejs`. Hiermee kunnen we een ` height` kunnen geven voor het eindpunt van de animatie. Wij hebben de animatie zo gemaakt dat de dichte staat van het element het animatie eindpunt is.

2023-05-24 15:39 UTC, tfrijsewijk commented
Lokaal resolved and merged met https://github.com/dso-toolkit/dso-toolkit/commit/20508dcf2fb6c0157e84c9808952d775ae4b4a60

2023-05-24 15:39 UTC, closed without merging