#2110 Heading zonder marges
dso-toolkit/dso-toolkit pull request #2126
Opened 2023-05-22 13:07 UTC by LukeVerlaan

2023-05-24 10:42 UTC, tfrijsewijk requested changes

2023-05-24 10:42 UTC, tfrijsewijk commented on packages/dso-toolkit/src/components/headings/headings.scss
> +  &:not(.inline-heading) {
Onze classnames zijn altijd prefixed met `dso-`.

Ik weet dat we nog het rijtje `.h1-.h6` hebben, maar die komen nog wel 'n keertje. Nieuwe classes altijd prefixen 👍

2023-06-01 12:53 UTC, tfrijsewijk commented
@LukeVerlaan en @MYpenburg weten jullie wat de staat van deze PR is?

2023-06-01 12:58 UTC, LukeVerlaan commented
Deze kan gereviewed/getest worden.

2023-06-08 13:11 UTC, tfrijsewijk commented
Zoals vanmiddag na de refinement besproken: Dit gaan we net iets anders doen. Ik werk het originele issue bij.

2023-06-08 13:38 UTC, tfrijsewijk commented
@LukeVerlaan Ik heb het issue bijgewerkt, ik sluit dit issue. Wil jij de branch verwijderen als je 'm niet meer nodig hebt? Of dit PR opnieuw openen op dezelfde branch.. het maakt mij niet uit 🤷‍♂️

2023-06-08 13:38 UTC, closed without merging