#2083 storybook 7 update
dso-toolkit/dso-toolkit pull request #2177
Opened 2023-06-21 19:47 UTC by tfrijsewijk

2023-06-22 08:08 UTC, LukeVerlaan requested changes
Ik heb een commit gedaan om de tests in de build te fixen (verkeerde urls)

Nog 2 punten:
- De docs voor de form stories zijn stuk.
- Is het bewust dat de storybooks niet meer automatisch openen?

2023-06-22 08:08 UTC, LukeVerlaan commented on packages/react/.storybook/preview.ts
> +      // I have no idea what type this is, and how this works. /Th
:joy:

2023-06-22 08:08 UTC, LukeVerlaan commented on storybook/.storybook/main.ts
> +    // }
Zie vorige comments

2023-06-23 07:58 UTC, tfrijsewijk commented on packages/dso-toolkit/src/storybook/arg-types.type.ts
> +// };
Dat lijkt mij ook

2023-06-23 07:58 UTC, tfrijsewijk commented on packages/dso-toolkit/src/storybook/index.ts
> +// export { ArgTypes } from "./arg-types.type.js";
Jup

2023-06-23 07:59 UTC, tfrijsewijk commented on packages/react/.storybook/preview.ts
> +      // I have no idea what type this is, and how this works. /Th
Onbegrijpelijk stukje code.. Ik heb het 3 jaar geleden ingecheckt 🤷

2023-06-23 08:02 UTC, tfrijsewijk commented
@LukeVerlaan:

> De docs voor de form stories zijn stuk.

Goed gezien, ik ga kijken.

> Is het bewust dat de storybooks niet meer automatisch openen?

Nee, en ik vind het niet fijner.. Ik vermoed dat Storybook een nieuwe default heeft ingesteld en dat wij nu expliciet moeten aangeven dat we het wel weer willen.

Ik zal het aanzetten.

Dank voor de review! Ik kon het even niet meer aanzien, en het was ook nog gruwelijk laat. Ik zal hier vandaag met hernieuwde energie weer meer verder gaan. Wil jij dan weer reviewen?

2023-06-23 08:04 UTC, tfrijsewijk commented on packages/dso-toolkit/src/components/form/form.args.ts
> -    defaultValue: "Formulier",
Goed gevonden! Hoe lang hebben we die deprecated warning wel niet in de console voorbij zien komen.. 🤪

2023-06-23 15:03 UTC, tfrijsewijk commented on package.json
> +    "puppeteer-core@^2.1.1": "13.5.2"
`sb extract` maakt gebruik van Puppeteer.

`puppeteer-core` voorziet in een eigen browser, namelijk Chromium. Versie 2.1.1 werkt met Chromium 80, maar de code die Angular genereert is daar te modern voor. Met 13.5.2 installeren we Chromium 100. Wat ik overigens ook maar gewoon heb verzonnen.

2023-06-30 18:56 UTC, tfrijsewijk commented
@LukeVerlaan 

> De docs voor de form stories zijn stuk.

Gefixed. Ik moest daar nog de Markdown compiler aansluiten.

> Is het bewust dat de storybooks niet meer automatisch openen?

Nee, maar ik krijg het niet aan. Ik vermoed dat er een bugje in de storybook CLI zit. Ik zal over twee weken weer 'n update doen, wie weet werkt het dan weer. Vanaf nu moeten we handmatig de Storybook openen 🤷

2023-07-01 21:03 UTC, merged