#2161 viewer grid vdk layout
dso-toolkit/dso-toolkit pull request #2323
Opened 2023-09-14 08:57 UTC by LukeVerlaan

2023-09-15 10:16 UTC, tfrijsewijk commented
<!--
  2 failure:  First commit mess..., `node` failed.
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>First commit message fails format: #2161 Viewer Grid: VDK layout</td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>

  `node` failed.
  </td>
    </tr>
  </tbody>
</table>



### Log

<details>


```
Error:  TypeError: Cannot read properties of null (reading 'issueId')
    at dangerfile.ts:205:93
    at step (dangerfile.ts:33:23)
    at Object.next (dangerfile.ts:14:53)
    at fulfilled (dangerfile.ts:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
danger-results://tmp/danger-results-568a7efd.json
```


</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against b45929ebf418433fe35fb7ce2991f9ac9d2c4611
</p>

2023-09-19 08:35 UTC, anneke commented
Ik heb even gekeken naar de Danger.JS melding en volgens mij zou de eerste commit message dan moeten zijn `#2161 [Updated] Viewer Grid: VDK layout` :)

2023-09-19 08:40 UTC, LukeVerlaan commented
De haakjes met soort change inderdaad vergeten. Het zal dan `[Added]` worden.

2023-09-28 13:06 UTC, tfrijsewijk commented on packages/dso-toolkit/src/components/viewer-grid/viewer-grid.args.ts
> +    if: { arg: "mode", eq: "VDK" },
WOW!

2023-09-29 08:28 UTC, LukeVerlaan commented on packages/core/src/components/viewer-grid/viewer-grid.tsx
> +    if (this.mode === "VDK" && this.mapElement instanceof HTMLDivElement) {
instanceof versoepelen naar niet undefined

2023-10-02 18:39 UTC, tfrijsewijk requested changes

2023-10-02 18:53 UTC, merged