#2017 [Removed] Tooltip: HTML-CSS implementatie verwijderen
dso-toolkit/dso-toolkit pull request #2325
Opened 2023-09-15 07:42 UTC by HalloJo

2023-09-15 08:22 UTC, tfrijsewijk commented
<!--
  2 failure:  First commit mess..., CHANGELOG entry d...
  0 warning: 
  
  
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>First commit message issue title differs from GitHub issue title: "Tooltip: HTML-CSS implementatie verwijderen" vs. "Tooltip: Verwijderen HTML/CSS implementatie".</td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>CHANGELOG entry does not match format.</td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against c2b50f9909fe05eca46d1947fe21dd13f79b7033
</p>

2023-09-15 11:37 UTC, LukeVerlaan approved these changes

2023-09-19 08:30 UTC, anneke commented
Ik heb geprobeerd om de dangerJS melding op te lossen. Markdown links werken zo: `[label](link)`. Ik onthoud het altijd als: de tekst van de link zit in een soort ascii knop (de blokhaken), en waar die knop naar moet linken is een soort toevoeging erna (tussen haakjes) :)

2023-09-20 13:27 UTC, tfrijsewijk requested changes
Ruimt lekker op zo, heel fijn! Maar we gaan nog één stapje verder.. Zie comment

2023-09-20 13:27 UTC, tfrijsewijk commented on packages/core/src/components/tooltip/tooltip.mixins.scss
Deze file mag worden opgedoekt: Op de plekken waar de mixins worden gebruikt gaan we direct de styling inzetten.

De mixins gaan we nooit meer gebruiken, en als het goed is worden ze nu ook alleen maar in het Web Component gebruikt.

De variables mogen wel blijven bestaan.

De index file mag wat mij betreft ook weg. Mochten we vanuit andere Web Components op de Tooltip variables willen gebruiken, kunnen we altijd nog bedenken of we direct naar `variables.scss` verwijzen

2023-09-21 08:57 UTC, anneke commented on packages/core/src/components/tooltip/tooltip.mixins.scss
Volgens mij is hier aan voldaan nu @tfrijsewijk

2023-09-23 10:15 UTC, tfrijsewijk commented on packages/core/src/components/tooltip/tooltip.mixins.scss
Ja! 🎉

2023-09-23 10:20 UTC, merged