#2235 form new required indicator
dso-toolkit/dso-toolkit pull request #2441
Opened 2023-11-21 13:09 UTC by hansgrimm

WIP: asterisk niet zichtbaar op icon pagina. wel in de lijst, maar geen preview

2023-11-21 13:12 UTC, hansgrimm commented
![Scherm­afbeelding 2023-11-21 om 14 11 06](https://github.com/dso-toolkit/dso-toolkit/assets/506527/d88a25d0-aea1-4c4d-84df-aea2f0584ebb)

2023-11-21 13:15 UTC, tfrijsewijk commented
<!--
  1 failure:  Het gerelateerde ...
  0 warning: 
  
  
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Het gerelateerde GitHub-issue mist het juiste label. Ik denk dat dat 'change' moet zijn. Kun je deze alsjeblieft toevoegen?</td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 1d19383c20a42bb9d2505bcc74bd4d49d8cc5bd8
</p>

2023-11-21 14:14 UTC, hansgrimm commented
![Scherm­afbeelding 2023-11-21 om 15 14 05](https://github.com/dso-toolkit/dso-toolkit/assets/506527/403324f6-6db1-43e3-80da-48cdadb1152d)
de SVG is leeg. hoe verhelp ik dat?

2023-11-22 10:35 UTC, tfrijsewijk commented
<!--
  1 failure:  Het lijkt erop da...
  0 warning: 
  
  
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Het lijkt erop dat je geen aantekening hebt toegevoegd aan het CHANGELOG. Lees de [Change management notatie](https://www.dso-toolkit.nl/master/voor-maintainers/change-management-notatie) om te lezen wat dit inhoudt en hoe je dit op de juiste manier doet.
  </td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 36bef7d5dd2c3889cfafaab90ac5a15d9b97632b
</p>

2023-11-23 14:30 UTC, hansgrimm commented
@tfrijsewijk bedankt! dit was voor mij kennelijk 'hidden in plain sight'. Is er een manier om dat te automatiseren? het is zo te zien alleen voor de iconenpagina, want verder werkt het prima zonder die aanpassing.

2023-11-23 19:56 UTC, tfrijsewijk commented
> @tfrijsewijk bedankt! dit was voor mij kennelijk 'hidden in plain sight'. Is er een manier om dat te automatiseren? het is zo te zien alleen voor de iconenpagina, want verder werkt het prima zonder die aanpassing.

Nee, dit is (redelijkerwijs) niet te automatiseren. Waar het om gaat is dat het nieuwe icoon aan de bundler van Stencil moet worden meegegeven. 

En dat is meteen de reden waarom het niet alleen op de iconen pagina niet werkte, maar uberhaupt niet in `<dso-icon>` had gewerkt: Het icoon was niet gebundled. In de console zie je ook een melding, iets in de richting van "unknown icon 'asterisk'.

2023-11-24 08:35 UTC, tfrijsewijk requested changes

2023-11-24 18:40 UTC, tfrijsewijk approved these changes

2023-11-24 18:40 UTC, merged