#2294 List Button: Trefwoorden worden niet voorgelezen als onderdeel van het resultaat/werkzaamheid.
dso-toolkit/dso-toolkit pull request #2501
Opened 2024-01-09 14:06 UTC by iterox

2024-01-10 10:17 UTC, tfrijsewijk requested changes

2024-01-10 10:17 UTC, tfrijsewijk commented on packages/core/src/components/list-button/list-button.tsx
> +    this.mutationObserver = new MutationObserver(() => {
En dan nog voor jouw beeldvorming: In het verleden hebben we performance problemen gehad met heel veel MutationObservers. DOM mutaties observen is best een kostbare aangelegenheid. Hetzelfde geldt voor ResizeObserver en IntersectionObserver. Eén is niet zo'n groot probleem, maar als er ineens 1000 staan gaan we het merken.

Dit kwam doordat het toolkit component met heel veel tegelijkertijd werden ingezet.

Een poging om dit te optimaliseren was door de IntersectionObserver en MutationObservers buiten de component instantie te plaatsen. Er is vervolgens maar één instantie die voor alle component instanties wordt gebruikt. Ik heb mijn vraagtekens bij deze optimalisatie omdat vervolgens alle component instanties maar één event listener hebben.

ResizeObserver kent geen `.unobserve()` waardoor het niet mogelijk is om één element (component instantie) te unobserven. Daardoor kan de ResizeObserver alleen maar onderdeel zijn van de component instantie.

Dit is slechts een FYI, hier hebben we in het verleden problemen mee gehad en ik denk dat het goed is dat jij dit ook weet/paraat hebt.

2024-01-11 07:47 UTC, iterox commented on packages/core/src/components/list-button/list-button.tsx
> +    this.mutationObserver = new MutationObserver(() => {
Fijne feedback.

Ik zie ook een aantal componenten, waarin de lifecycle-method componentDitRender wordt gebruikt om de MutationOberver te instantiëren. In deze PR heb ik connectedCallback nu gebruikt

2024-01-11 09:13 UTC, iterox commented on packages/core/src/components/list-button/list-button.tsx
> +                {this.subcontentPrefix}
Als wij de : invoegen na de this.subcontentPrefix dan is ie gegarandeerd. Als we het aan de afnemers overlaten dan is de voorleeservaring mogelijk minder optimaal. Voor nu heb ik de : ingevoegd. Dan kan Tim dat beoordelen wanneer ik hem de link naar de list-button in deze branch-release geef.

2024-01-11 15:50 UTC, tfrijsewijk commented
<!--
  1 failure:  Je CHANGELOG-aant...
  0 warning: 
  
  
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Je CHANGELOG-aantekening staat niet onder het kopje van de eerstvolgende release ('Next'), maar onder '🚙 62.9.0'. Verplaats deze naar de juiste locatie, zodat wanneer je pull-verzoek wordt samengevoegd, de CHANGELOG-geschiedenis correct je werk weergeeft in de juiste release.</td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 017686ea7b04fda628992a764191517ffe9bb3fd
</p>

2024-01-11 18:51 UTC, tfrijsewijk commented on packages/core/src/components/list-button/list-button.tsx
> +    this.mutationObserver = new MutationObserver(() => {
> Ik zie ook een aantal componenten, waarin de lifecycle-method componentDitRender wordt gebruikt om de MutationOberver te instantiëren. In deze PR heb ik connectedCallback nu gebruikt

Hier moeten we eens 'n keer één lijn in maken. Voel jij je geroepen om een overzichtje te maken? ;-)

2024-01-11 18:51 UTC, tfrijsewijk commented on packages/core/src/components/list-button/list-button.tsx
> +                {this.subcontentPrefix}
Prima!

2024-01-11 19:08 UTC, tfrijsewijk reviewed
OK, ziet er goed uit! Technisch ✅ , het hangt nu op hoe Tim dit ontvangt.

2024-01-11 19:10 UTC, tfrijsewijk approved these changes

2024-01-21 19:28 UTC, tfrijsewijk approved these changes

2024-01-21 19:28 UTC, merged