#2500 [Fixed] Document Component: Ondersteuning lijstnummers IMRO documenten
dso-toolkit/dso-toolkit pull request #2624
Opened 2024-04-11 17:33 UTC by tfrijsewijk

2024-04-11 17:49 UTC, tfrijsewijk reviewed
In de toolkit is alles een component. Als het geen component is, is het onderdeel van een ander component (componenten die specifiek in andere componenten mogen, hebben we wel eens liefkozend "sub componenten" genoemd, maar dit is geen officiele term die in de architectuur terugkomt).

Dus, alles is een component.

Document Component is een (zelfstandig) component. Maar om een document van Document Components te maken moet er aan bepaalde markup voldoen. Specifiek hebben we het over een lijst met items.

Deze lijst van Document Components moest ook nog eens in een Responsive Element worden gezet.

Deze "extra" markup voorschriften waren onderdeel van de markup voorschriften van Document Component. En hier ging het 'n beetje mis. De hierachie was:

```html
<dso-responsive-element class="dso-document-components">
  <ul>
    <li>
      <dso-document-component>
        <ul>
          <li>
            <dso-document-component>
              <!-- etc -->
```

Maar als alles een component is, of anders onderdeel van een component is: _Waar_ hoort

```html
<dso-document-component class="dso-document-components">
  <ul>
    <li>
```

dan bij? Het kan geen onderdeel van Document Component zijn, die begint immers bij `<dso-document-component>`.

Dit PR moet deze tekortkoming oplossen. Ik heb een nieuw component "Document Component List" geintroduceerd. Dit is alleen op code niveau/organisatie gedaan, er is geen Storybook etalage. Dit omdat Document Component gedemoed wordt met een "demo component" (uniek in zijn soort, maar ook ongewenst): `<dsot-document-component-demo>`.

Zie het PR voor verdere toelichting. Ik heb de comments toegevoegd voor de reviewer(s). Degene die merged mag de comments resolven.

2024-04-11 17:49 UTC, tfrijsewijk commented on packages/dso-toolkit/src/components/document-component-list/document-component-list.scss
> +  > li + li {
Deze code is copy/pasted uit `document-component.scss`, maar deze regel code was eerst `li + li {`.

Met de direct child selector wordt alleen de `li` horende bij Document Component List (`ul.dso-document-list`) gestijld.

2024-04-11 17:49 UTC, tfrijsewijk commented on packages/dso-toolkit/src/components/document-component-list/document-component-list.scss
> +ul.dso-document-component-list {
Deze code is copy pasted uit `document-component.scss`, maar deze regel code was eerst `.dso-document-components`.

De voorgeschreven markup was eerst:

```html
<dso-responsive-element class="dso-document-components">
  <ul>
    <li>
      <dso-document-component>
```

en wordt nu:

```html
<dso-responsive-element class="dso-document-components">
  <ul class="dso-document-list">
    <li>
      <dso-document-component>
```

2024-04-11 17:49 UTC, tfrijsewijk commented on packages/dso-toolkit/src/components/document-component/document-component.scss
> +dso-responsive-element.dso-document-components {
In de praktijk werd deze markup al voorgeschreven. Met deze change is de intentie van de stijling duidelijker.

2024-04-12 08:49 UTC, iterox commented
De blauwe markering is omgekeerd.
<img width="2555" alt="Screenshot 2024-04-12 at 10 46 04" src="https://github.com/dso-toolkit/dso-toolkit/assets/4646174/949ec1f4-2dbf-49ee-ba66-b08c6c97b11e">

2024-04-12 08:49 UTC, iterox commented
De inspringing is weg
<img width="2552" alt="Screenshot 2024-04-12 at 10 46 27" src="https://github.com/dso-toolkit/dso-toolkit/assets/4646174/60f8b11b-de93-41ae-884b-44caa812fc32">

2024-04-12 08:50 UTC, iterox requested changes
Ik constateer 2 opvallende verschillen

2024-04-12 10:55 UTC, tfrijsewijk commented
> De blauwe markering is omgekeerd. <img alt="Screenshot 2024-04-12 at 10 46 04" width="2000" src="https://private-user-images.githubusercontent.com/4646174/321923326-949ec1f4-2dbf-49ee-ba66-b08c6c97b11e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MTk1MTMsIm5iZiI6MTcxMjkxOTIxMywicGF0aCI6Ii80NjQ2MTc0LzMyMTkyMzMyNi05NDllYzFmNC0yZGJmLTQ5ZWUtYmE2Ni1iMDhjNmM5N2IxMWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTJUMTA1MzMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjcxODZhZTA4MzI5MzgxZjkwMWViMjdlNjIzMDc3MjkwNDJiMzc0YmVmZTk3ZDBjZjU2MTk3MDM5ZGMzMjk3NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.BsGKWyRgFbgUIzrxRhKggB2djUlTdWQCuEth-B231FE">

De blauwe markering is randomized, net zoals notApplicatie: https://github.com/dso-toolkit/dso-toolkit/blob/master/packages/core/src/components/document-component-demo/document-component.demo.tsx#L130. Deze data is namelijk geen onderdeel van het Ozon document, en om toch enigszins een representatief gevoel te hebben tijdens het ontwikkelen heb ik dit maar gedaan.



> De inspringing is weg <img alt="Screenshot 2024-04-12 at 10 46 27" width="2000" src="https://private-user-images.githubusercontent.com/4646174/321923486-60f8b11b-de93-41ae-884b-44caa812fc32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MTk1MTMsIm5iZiI6MTcxMjkxOTIxMywicGF0aCI6Ii80NjQ2MTc0LzMyMTkyMzQ4Ni02MGY4YjExYi1kZTkzLTQxYWUtODg0Yi00NGNhYTgxMmZjMzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTJUMTA1MzMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGNlZTJiYjQ4MWJlNWNmMjZkYzk4OGU4MGUwYWY2NTRkYTgzZTBkYTQzYWUwODc1NmQxYjgzZWNhZWZlYmMzYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.dZcSQ5d2a4MNKiIwmbhCV2IXWNynjNthMJHDfBKGpmY">

Maar dit is zeker niet de bedoeling en ga ik naar kijken 🙏

2024-04-12 11:59 UTC, tfrijsewijk commented
@iterox Opgelost! Zie https://github.com/dso-toolkit/dso-toolkit/pull/2624/commits/e1e86092a45778ef98f242276ccfa3cabfd9cc1c. Goed gevonden.

2024-04-15 08:30 UTC, iterox approved these changes

2024-04-15 08:31 UTC, merged