#2498 blog en fixes voor Logo component
dso-toolkit/dso-toolkit pull request #2670
Opened 2024-05-14 11:00 UTC by iterox

Heb deze PR klaar gezet, zodat de fixes voor de verkeerde uitlijning van de ribbon en de blog post over de nieuwe mogelijkheden van het Logo component.

Dienen we de issue trouwens niet te hernoemen?

Nu: `Header: Aparte link voor applicatienaam in compacte header`

Voorstel: `Logo: Aparte link voor applicatienaam`

2024-05-14 11:00 UTC, tfrijsewijk commented
<!--
  1 failure:  De eerste commit ...
  0 warning: 
  
  
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  De eerste commit ('#2498 blog en fixes voor Logo component') volgt niet de vereiste formule. Lees de [Change management notatie](https://www.dso-toolkit.nl/master/voor-maintainers/change-management-notatie) voor voorbeelden van wat het moet zijn, en uitleg waarom.
  </td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 0721a91ba0c854b10385a7c8550da9b8eca73046
</p>

2024-05-14 12:43 UTC, tfrijsewijk requested changes

2024-05-14 12:43 UTC, tfrijsewijk commented on packages/core/src/components/logo/logo.scss
> +  :host([logo-url][ribbon]) {
Om dit goed te laten werken moet `@Prop() ribbon` ook als attribuut worden gereflecteerd, zie https://github.com/dso-toolkit/dso-toolkit/blob/master/packages/core/src/components/logo/logo.tsx#L58

2024-05-14 16:31 UTC, tfrijsewijk approved these changes

2024-05-14 16:32 UTC, tfrijsewijk commented
@hansgrimm kan jij de CSS reviewen?

2024-05-14 19:47 UTC, hansgrimm commented
build gefaald, dus ik kijk morgen verder.

2024-05-15 06:46 UTC, iterox commented
> Logo: Aparte link voor applicatienaam

Titel van Issue, commit message op master en changelog, dacht ik, toch?

2024-05-15 07:26 UTC, iterox commented
Dit is lokaal gemerged met deze commit [Logo: Aparte link voor applicatienaam](https://github.com/dso-toolkit/dso-toolkit/commit/26ab6f1c4ca746c6d37a990550524b75e48587d9)

2024-05-15 07:26 UTC, closed without merging