#2316 Storybook: `storiesOf()` naar CSF
dso-toolkit/dso-toolkit pull request #2684
Opened 2024-06-03 14:58 UTC by iterox

- card
- card-container

2024-06-03 14:59 UTC, tfrijsewijk commented
<!--
  1 failure:  Het scopegedeelte...
  0 warning: 
  
  
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Het scopegedeelte en de samenvatting in je eerste commit-bericht moeten overeenkomen met de titel van het GitHub-issue, maar dat doen ze momenteel niet: Vergelijk 'Storybook: storiesOf() naar CSF' met de titel van het issue: 'Storybook: `storiesOf()` naar CSF'.
  </td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against fe074d50d763700a0f43196432de41baef1f712a
</p>

2024-06-13 08:31 UTC, iterox commented
De build faalt ivm 2 screenshot verschillen:

De verschillen worden verklaard door een fix op de css-template van card, waarbij false in de pagina verscheen als er geen interactions waren: daar is in deze pr een ternary voor gemaakt die bij de afwezigheid van interactions naar false resolved
![html-css-card-list--card-list diff](https://github.com/dso-toolkit/dso-toolkit/assets/4646174/b0740db7-fd89-45ef-8330-94e9b4c6343f)

De verschillen worden verklaard door een fix op de css-template van card, waarbij voorheen de anchor niet getoond werd voor alle href-stroies van card:
![html-css-card-grid--card-grid diff](https://github.com/dso-toolkit/dso-toolkit/assets/4646174/000bf51e-ea1b-4fbb-8c58-d71940624967)

Is dit nu het mechanisme waarmee we screenshot verschillen duiden, verklaren en accepteren?
@tfrijsewijk

2024-06-18 16:08 UTC, tfrijsewijk commented
Ja, het ziet er fraai uit 🤷 👍

2024-06-19 08:45 UTC, tfrijsewijk requested changes
Ik zal ff naar die TS gerelateerde issues kijken

2024-06-19 08:45 UTC, tfrijsewijk commented on angular-workspace/components/expandable/expandable.stories.ts
> +  /* TODO: Hoi Thomas, je zult tegen deze Todo aan gaan lopen en ik heb nogal wat moeite om de typeringen van de
Message in a bottle! 😄

2024-06-19 08:45 UTC, tfrijsewijk commented on packages/dso-toolkit/src/components/card/card.args.ts
> +      // @ts-expect-error don't know
Ff naar kijken dus, komt goed :+1:

2024-06-19 08:45 UTC, tfrijsewijk commented on packages/dso-toolkit/src/components/date-picker-legacy/date-picker-legacy.stories-of.ts
> +  datePickerLegacyArgTypes,
goed gezien!

2024-06-19 08:45 UTC, tfrijsewijk commented on packages/react/src/components/date-picker-legacy/date-picker-legacy.stories.tsx
> +    // @ts-expect-error on story(): TS2571: Object is of type `unknown` */}
Gaan we ook naar kijken

2024-06-19 08:45 UTC, tfrijsewijk commented on packages/react/src/components/date-picker/date-picker.stories.tsx
> +    // @ts-expect-error on story(): TS2571: Object is of type `unknown` */}
Check

2024-06-19 08:45 UTC, tfrijsewijk commented on packages/react/src/components/expandable/expandable.stories.tsx
> +import type { Meta } from "@storybook/web-components";
React Storybook importeert uit `@storybook/react`

2024-06-19 11:54 UTC, tfrijsewijk commented on packages/dso-toolkit/src/components/toggletip/toggletip.models.ts
> +  children: TemplateFnReturnType | string;
Hier heb ik 'n beetje vals gespeeld. In principe is dit niet iets wat we willen, `children` is immers een framework node. Maar omdat die Angular Storybook ons nu dusdanig in de weg zit is dit ff makkelijker.

2024-06-19 11:55 UTC, tfrijsewijk commented on angular-workspace/components/helpers.ts
> +export function isStoryFnAngularReturnTypeTemplate(
React biedt een check aan, voor Angular moesten we 'm ff zelf bakken.

Gelukkig heb je je toevallig in type guards ingelezen ;P

2024-06-20 09:47 UTC, iterox commented on packages/dso-toolkit/src/components/card-container/card-container.args.ts
> +export const cardContainerArgs: { cards: CardArgs[] } = {
Gedaan.

2024-06-20 09:49 UTC, iterox commented on angular-workspace/components/expandable/expandable.stories.ts
> +import { type Meta } from "@storybook/web-components";
Gedaan

2024-06-20 09:51 UTC, iterox commented on packages/react/src/components/expandable/expandable.stories.tsx
> +import type { Meta } from "@storybook/web-components";
Gedaan

2024-06-20 13:12 UTC, tfrijsewijk commented on angular-workspace/components/expandable/expandable.stories.ts
> +// import { decorator } from "./expandable.decorator";
Deze kan nog weg

2024-06-20 13:40 UTC, iterox commented on angular-workspace/components/expandable/expandable.stories.ts
> +// import { decorator } from "./expandable.decorator";
Gedaan

2024-06-20 13:42 UTC, iterox commented
> @iterox Ziet er goed uit. Had je mijn begeleidende teksten bij mijn suggesties nog gelezen?
> 
> Verder moeten we opletten hoe we dit mergen, zodat het werk van Hans ihkv #2366 samen blijft..

Ik heb je suggesties gelezen. Denk ik. Welke bedoel je eigenlijk? 

Hans' merged eerst in de laatste commit op master, toch? Dan moet dat eerst en daarna de rest.

2024-06-21 11:22 UTC, merged