#2779 project item
dso-toolkit/dso-toolkit pull request #2809
Opened 2024-09-23 19:59 UTC by tfrijsewijk

2024-09-23 20:00 UTC, tfrijsewijk commented
<!--
  2 failure:  Het scopegedeelte..., Het scopegedeelte...
  0 warning: 
  
  
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Het scopegedeelte en de samenvatting in je eerste commit-bericht moeten overeenkomen met de titel van het GitHub-issue, maar dat doen ze momenteel niet: Vergelijk 'Project Item: Nieuw component' met de titel van het issue: 'Projects Item: Nieuw component'.</td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>

  Het scopegedeelte van je eerste commit-bericht ('Project Item') verschilt van de scope in het CHANGELOG ('Projects Item'). Het toevoegen van het juiste scopegedeelte maakt het gemakkelijker om later in het CHANGELOG te zien welke wijzigingen er zijn aangebracht aan een specifiek aspect van de codebase. Voor meer informatie, raadpleeg de [Change management-notatie](https://www.dso-toolkit.nl/master/voor-maintainers/change-management-notatie).
  </td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against e1b59117a3238de67ca524ebb0deb029d068cfab
</p>

2024-09-24 06:51 UTC, iterox commented
Denk nog work in progress:

<img width="740" alt="Screenshot 2024-09-24 at 08 49 57" src="https://github.com/user-attachments/assets/f97dff54-2fc9-4fb2-8c5d-d28bd5913a65">

2024-09-24 06:51 UTC, iterox requested changes
Geen bijzonderheden. Nog work in progress.

2024-09-24 06:51 UTC, iterox commented on packages/core/src/components/project-item/project-item.tsx
> +// import {  } from "./project-item.interfaces";
commented import

2024-09-24 06:51 UTC, iterox commented on packages/core/src/components/project-item/project-item.interfaces.ts
It's empty

2024-09-24 11:23 UTC, hansgrimm commented
Om de boel goed neer te zetten qua styling, heb ik deze indeling nodig qua coontainers:
<img width="1180" alt="361438091-8634fa65-04ef-4241-aa89-99e52db332bd" src="https://github.com/user-attachments/assets/234246cb-1432-4f44-8bf2-23de61d38b99">
Kan ik dat zelf doen in de tsx? dat zou een hoop schelen

2024-09-24 11:43 UTC, hansgrimm commented
zo wil ik het hebben om ordentelijk te kunnen layouten:
```html
<dso-project-item>
<div class="project-item-header">
</div>
</dso-project-item>
```

2024-09-26 14:33 UTC, iterox requested changes

2024-09-26 14:33 UTC, iterox commented on packages/dso-toolkit/src/components/project-item/project-item.args.ts
> +// eslint-disable-next-line @typescript-eslint/no-explicit-any -- Weghalen voor mergen!!
?

2024-09-26 18:32 UTC, hansgrimm commented on packages/core/src/components/project-item/project-item.scss
En dat heeft het ook (.875rem)

2024-09-26 18:33 UTC, hansgrimm commented on packages/core/src/components/project-item/project-item.tsx
> +            <slot name="progress" />
Daar moet nog een ei over gelegd worden

2024-09-26 18:53 UTC, hansgrimm commented on packages/core/src/components/project-item/project-item.scss
Haha, dat dacht ik. Vergeten een custom property naam aan te passen (dsot prefix). Gefixt.

2024-09-27 08:21 UTC, hansgrimm commented
Styling voor `<mark>` is toegevoegd. Deze is afwijkend van de standaard versie: geen achtergrondkleur/padding, bold tekst.
De `<mark>` tags moeten in deze constructie om de tekst zelf gezet worden.

2024-09-27 08:22 UTC, hansgrimm commented on packages/core/src/components/project-item/project-item.tsx
> +            <slot name="progress" />
styling voor `<mark>` is iig toegevoegd.

2024-09-27 10:54 UTC, iterox commented
Todo: e2e test

2024-09-27 10:54 UTC, iterox requested changes
E2e test ontbreekt nog

2024-09-27 12:15 UTC, tfrijsewijk commented on packages/dso-toolkit/src/components/project-item/project-item.args.ts
> +// eslint-disable-next-line @typescript-eslint/no-explicit-any -- Weghalen voor mergen!!
Dat er een degelijk type komt

2024-09-29 18:38 UTC, tfrijsewijk commented on packages/core/src/components/project-item/project-item.tsx
> +// import {  } from "./project-item.interfaces";
Weggehaald

2024-09-29 18:38 UTC, tfrijsewijk commented on packages/core/src/components/project-item/project-item.interfaces.ts
Verwijderd

2024-09-29 20:08 UTC, tfrijsewijk commented on packages/core/src/components/project-item/readme.md
> +# dso-project-item
`<dso-project-item>`

2024-09-30 06:00 UTC, merged