#2836 [Added] Document Component: Renvooiweergave kenmerken paneel
dso-toolkit/dso-toolkit pull request #2870
Opened 2024-11-07 20:23 UTC by tfrijsewijk

2024-11-07 20:23 UTC, tfrijsewijk commented
<!--
  1 failure:  Je CHANGELOG-aant...
  0 warning: 
  
  
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Je CHANGELOG-aantekening staat niet onder het kopje van de eerstvolgende release ('Next'), maar onder '🆓 Release 65.1.0 - 2024-11-08'. Verplaats deze naar de juiste locatie, zodat wanneer je pull-verzoek wordt samengevoegd, de CHANGELOG-geschiedenis correct je werk weergeeft in de juiste release.</td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 7bb3e2efa02dec6e761d755d5a7bdb2acb7d90d3
</p>

2024-11-07 20:25 UTC, tfrijsewijk commented
Deze commit faalt door Danger, maar ik jullie duidelijk maken dat dit een tussenrelease gaat worden. Misschien dat ik er nog 'n testje bij ga schrijven, maar in de basis is dit wat het is. We kunnen 'm pair-reviewen?

2024-11-08 07:20 UTC, iterox requested changes
Denk dat het er goed uitziet.

Allen dat dit in release 65.1.0 zit begrijp ik niet. Moet 66.2.0 zijn.

2024-11-08 13:56 UTC, tfrijsewijk commented
> Denk dat het er goed uitziet.
> 
> Alleen dat dit in release 65.1.0 zit begrijp ik niet. Je schrijft tussenrelease. Maar waarom?

De viewer wilt deze change graag in de 65 versiereeks ontvangen. Ze willen dinsdag releasen en het lukt ze niet om in 1 dag van 65.0.2 naar 66.2.0 te gaan, met name vanwege de impact van de Card opsplitsing in #2797.

2024-11-09 08:32 UTC, tfrijsewijk commented on CHANGELOG.md
> +## 🆓 Release 65.1.0 - 2024-11-08
De viewer heeft deze change op 65 besteld omdat ze update naar 66 in een andere branch doen

2024-11-09 09:25 UTC, closed without merging