#2857 accordion  renvooi titel accordion
dso-toolkit/dso-toolkit pull request #2906
Opened 2024-11-29 13:20 UTC by cvanderleij-ilionx

2024-11-29 16:51 UTC, tfrijsewijk commented
<!--
  1 failure:  Je CHANGELOG-aant...
  0 warning: 
  
  
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Je CHANGELOG-aantekening staat niet onder het kopje van de eerstvolgende release ('Next'), maar onder '✍️ Release 67.0.0 - 2024-11-25'. Verplaats deze naar de juiste locatie, zodat wanneer je pull-verzoek wordt samengevoegd, de CHANGELOG-geschiedenis correct je werk weergeeft in de juiste release.</td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 7e51ea19b852ec050cc036d9a5db0e8c7704e4e5
</p>

2024-12-03 10:30 UTC, cvanderleij-ilionx commented on packages/dso-toolkit/src/components/accordion/accordion.models.ts
> +  handleTitle: RenvooiValue;
Een renvooiValue mag ook een string zijn

2024-12-03 16:31 UTC, iterox requested changes

2024-12-03 16:31 UTC, iterox commented on packages/dso-toolkit/src/components/accordion/accordion.stories-of.ts
> +        handleTitleText: "Attention",
Ik vraag mij af of dit nog een functie heeft?

2024-12-03 16:31 UTC, iterox commented on storybook/cypress/e2e/accordion.cy.ts
> +    cy.get("dso-accordion")
Dit is nou zo'n cypress file waarin het gebruikt van `.hydrated` niet volledig is doorgevoerd. Zou nu wel een mooie gelegenheid zijn.

2024-12-03 16:31 UTC, iterox commented on storybook/src/components/accordion/accordion.core-template.ts
> +                change-action=${changeAction}
wijzigactie

2024-12-03 16:31 UTC, iterox commented on storybook/src/components/accordion/accordion.css-template.ts
> +              ? html`<dso-renvooi .value=${section.handleTitle}></dso-renvooi>`
Hier willen we de renvooiTemplate hanteren.

2024-12-03 16:31 UTC, iterox commented on packages/react/src/components/accordion/accordion.stories.tsx
> +      renvooiSections: subSections(templates),
Waarom hier niet de renvooiSections? Mss moeten we deze functionaliteit in zijn geheel niet willen etaleren, omdat de React afnemers er toch niets mee doen.

2024-12-04 12:49 UTC, iterox commented on storybook/src/components/accordion/accordion.content.ts
> +    changeAction: "voegtoe",
Gedaan.

2024-12-04 13:15 UTC, iterox commented on packages/react/src/components/accordion/accordion.stories.tsx
> +      renvooiSections: subSections(templates),
Ah. Ik snap hem. We etaleren idd de story `RenvooiSections` niet in de React Stoprybook. ✅  Moeten uiteraard wel een `storyTemplates`-function retourneren die een `renvooiSections` retourneert.

2024-12-04 13:15 UTC, iterox commented on storybook/src/components/accordion/accordion.css-template.ts
> +              ? html`<dso-renvooi .value=${section.handleTitle}></dso-renvooi>`
Gedaan

2024-12-04 13:38 UTC, iterox commented on storybook/cypress/e2e/accordion.cy.ts
> +    cy.get("dso-accordion")
Gedaan

2024-12-04 13:39 UTC, iterox commented on packages/dso-toolkit/src/components/accordion/accordion.args.ts
> +  wijzigActie: AnnotationWijzigactie | undefined;
Gedaan

2024-12-04 13:39 UTC, iterox commented on packages/core/src/components/accordion/components/accordion-section.tsx
> +  changeAction: AnnotationWijzigactie | undefined;
Aangepast

2024-12-04 13:39 UTC, iterox commented on packages/dso-toolkit/src/components/accordion/accordion.models.ts
Gedaan

2024-12-04 13:40 UTC, iterox commented on packages/core/src/components/accordion/components/accordion-section.tsx
> +import { AnnotationWijzigactie } from "dso-toolkit";
Gedaan

2024-12-04 15:20 UTC, tfrijsewijk requested changes
Gaat goed! Laatste overwegingen, zie feedback

2024-12-05 06:44 UTC, iterox commented on CHANGELOG.md
> +
Weggehaald.

2024-12-05 06:45 UTC, iterox commented on packages/core/src/components/accordion/components/accordion-section.tsx
> +  EventEmitter,
@Chris heeft de Optimize imports aangezet in zijn webstorm en dus wordt het alfabetisch, wanneer hij een file aanraakt.

2024-12-05 06:46 UTC, iterox commented on packages/core/src/components/accordion/components/accordion-section.tsx
> +  @Prop({ reflect: true })
Weggehaald

2024-12-05 06:48 UTC, iterox commented on packages/core/src/components/accordion/components/accordion-section.tsx
> +          ["dso-accordion-wijzig-actie-" + this.wijzigactie]: !!this.wijzigactie,
Aangepast

2024-12-05 06:49 UTC, iterox commented on packages/core/src/components/accordion/components/accordion-section.tsx
> +   * An optional 'wijzigactie' that signals if the contents of the section is added or removed.
Aangepast

2024-12-05 06:50 UTC, iterox commented on storybook/cypress/e2e/accordion.cy.ts
> +      .and("have.text", "Dit is toegevoegde tekst");
ok.

2024-12-05 06:52 UTC, iterox commented on storybook/cypress/e2e/accordion.cy.ts
> +      .find("dso-accordion-section:nth-child(2)")
Aangepast

2024-12-05 06:52 UTC, iterox commented on storybook/cypress/e2e/accordion.cy.ts
> +      .invoke("prop", "handleTitle", { was: "Dit was de tekst", wordt: "Dit is de tekst" })
Weggehaald

2024-12-05 06:54 UTC, iterox commented on storybook/src/components/accordion/accordion.css-template.ts
> +            : nothing}
Aangepast

2024-12-05 06:54 UTC, iterox commented on storybook/cypress/e2e/accordion.cy.ts
> +      .get("@accordionSection")
Aangepast

2024-12-05 09:12 UTC, tfrijsewijk commented on packages/core/src/components/accordion/components/accordion-section.tsx
> +  EventEmitter,
Ok, laten we het binnenkort eens hebben over dit soort collateral changes

2024-12-05 09:18 UTC, tfrijsewijk commented on storybook/cypress/e2e/accordion.cy.ts
> +      .find("dso-accordion-section:nth-child(2)")
Op regel 215 (deze), 229 en 249 zie ik nog dezelfde constructie staan.

2024-12-05 09:19 UTC, tfrijsewijk commented on storybook/src/components/accordion/accordion.css-template.ts
> +            : html`${section.handleTitle}`}
Er schiet mij nog iets te binnen, volgens mij mag dit ook:

```suggestion
          ${typeof section.handleTitle !== "string"
            ? renvooiTemplate({ value: section.handleTitle })
            : section.handleTitle
```

Wat vinden jullie, duidelijker?

2024-12-05 14:03 UTC, iterox commented on storybook/src/components/accordion/accordion.css-template.ts
> +            : html`${section.handleTitle}`}
Aangepast

2024-12-05 14:05 UTC, tfrijsewijk submitted a review, later dismissed
🚢 🇮🇹

2024-12-05 15:26 UTC, merged