#2912 [Fixed] Document Component: Accessible name voor tonen/verbergen kenmerken zijn onjuist
dso-toolkit/dso-toolkit pull request #2913
Opened 2024-12-04 21:07 UTC by tfrijsewijk

2024-12-04 21:10 UTC, tfrijsewijk reviewed
Tevens heb ik Panel voorzien van i18n.

2024-12-04 21:10 UTC, tfrijsewijk commented on packages/core/src/components/document-component/document-component.tsx
> +                <span id="heading-title">
Tijdens het ontwikkelen zag ik dat er een `<div>` in de heading zat. Opgelost met deze `span` en `display: block;`.

2024-12-05 06:40 UTC, iterox requested changes

2024-12-05 06:40 UTC, iterox commented on packages/core/src/components/panel/panel.i18n.ts
> +      close: "Sluiten",
Close

2024-12-05 06:40 UTC, iterox commented on packages/core/src/components/panel/panel.i18n.ts
> +      close: "Close",
Sluiten

2024-12-05 09:08 UTC, tfrijsewijk commented on packages/core/src/components/panel/panel.i18n.ts
> +      close: "Sluiten",
😆

2024-12-05 09:25 UTC, iterox approved these changes

2024-12-05 17:23 UTC, merged