#698 version selector as theme component
dso-toolkit/dso-toolkit pull request #740
Opened 2020-08-25 10:19 UTC by benheldoorn

2020-08-26 12:38 UTC, tfrijsewijk requested changes
Ziet er goed uit, paar kleine opmerkingen. Ook ter test.

Er is een CI/CD pipeline, ook voor branches. Je kan jouw resultaat live bekijken: https://dso-toolkit.nl/_698-version-selector/

Als je de opmerkingen verwerkt hebt leggen we het bij Bram neer.

2020-08-26 12:38 UTC, tfrijsewijk commented on theme/js/components/version-selector.js
> +    const versionRequest = new XMLHttpRequest();
Nu we een bundler en module loader hebben kunnen we er ook voor kiezen om iets als `axios` te installeren en een `VersionService` te maken. Deze service zou dan ook in de global scope beschikbaar kunnen zijn zodat de versions pagina (https://dso-toolkit.nl/11.1.0/docs/versions.html) daar ook gebruik van maakt.. En die kan het resultaat cachen waardoor er maar één request naar versions.json wordt gedaan.

Wat denk je?

2020-08-26 12:38 UTC, tfrijsewijk commented on theme/js/components/version-selector.js
> +      '<li>' +
Waarom hier geen backtik / template literal gebruiken?

2020-08-26 12:38 UTC, tfrijsewijk commented on theme/js/components/version-selector.js
> +      '<li>' +
En zou je deze `li` van de classes `navbar-text dropdown` willen voorzien en de `div` op de volgende regel willen verwijderen?

![image](https://user-images.githubusercontent.com/9696261/91304107-41580c00-e7a9-11ea-877b-549cb67fdac7.png)

de status modifier `open` komt dus ook op de `li`.

Ik weet dat dit (nog) niet zo expliciet in de toolkit staat omschreven, maar ik wil kijken hoever we komen.

2020-08-26 12:38 UTC, tfrijsewijk commented on theme/js/components/version-selector.js
> +      '<button type="button" class="btn btn-default dropdown-toggle" id="version_selector_button" aria-haspopup="true" aria-expanded="true" />' +
`btn-default` graag vervangen met `btn-link`.

2020-09-07 07:27 UTC, benheldoorn commented
> Er is een CI/CD pipeline, ook voor branches. Je kan jouw resultaat live bekijken: https://dso-toolkit.nl/_698-version-selector/

Helaas is dit issue daar vrijwel niet te testen omdat het om de version selector gaat. Zodra je een andere versie kiest ga je ook naar die versie.

2020-09-11 11:59 UTC, tfrijsewijk commented on theme/js/components/version-selector.js
> +    const versionRequest = new XMLHttpRequest();
Doen we in ander issue

2020-09-11 11:59 UTC, tfrijsewijk approved these changes

2020-09-11 12:01 UTC, merged